# Generated by Django 4.2.1 on 2023-05-28 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Франшиза"
                    ),
                ),
                (
                    "typeshop",
                    models.CharField(
                        choices=[
                            ("Зоомагазин", "Зоомагазин"),
                            ("Аптека", "Аптека"),
                            ("Магазин одежды", "Магазин одежды"),
                            ("Товары для дома", "Товары для дома"),
                            ("Продуктовый", "Продуктовый"),
                        ],
                        default="Продуктовый",
                        max_length=20,
                        verbose_name="Тип мигазина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Франшиза",
                "verbose_name_plural": "Франшизы",
                "db_table": "Brand",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("крупы", "Крупы"),
                            ("молоко", "Молочная продукция"),
                            ("мясо", "Мясо"),
                            ("рыба", "Рыба"),
                            ("фрукты", "Фрукты"),
                            ("овощи", "Овощи"),
                            ("алкоголь", "Алкоголь"),
                        ],
                        default="молоко",
                        max_length=8,
                        verbose_name="Тип продукта:",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=30, verbose_name="Название товара: "),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание товара"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Цена за еденицу"
                    ),
                ),
                (
                    "shipment",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата поставки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "db_table": "Product",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "shop_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Название магазина"
                    ),
                ),
                ("addres", models.CharField(max_length=20, verbose_name="Адрес")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.brand",
                        verbose_name="Франшиза",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(related_name="Products", to="shop.product"),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "db_table": "Shop",
            },
        ),
    ]
