# Generated by Django 4.2.1 on 2023-05-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("крупы", "Крупы"),
                            ("молоко", "Молочная продукция"),
                            ("мясо", "Мясо"),
                            ("рыба", "Рыба"),
                            ("фрукты", "Фрукты"),
                            ("овощи", "Овощи"),
                        ],
                        default="молоко",
                        max_length=8,
                        verbose_name="Тип продукта:",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=30, verbose_name="Название товара: "),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание товара"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Цена за еденицу"
                    ),
                ),
                (
                    "shipment",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата поставки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "db_table": "Product",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Название магазина",
                    ),
                ),
                ("addres", models.CharField(max_length=20, verbose_name="Адрес")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "db_table": "Shop",
            },
        ),
    ]
