# Generated by Django 4.2.1 on 2023-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="products",
            field=models.ManyToManyField(related_name="shops", to="shop.product"),
        ),
    ]
