# Generated by Django 4.2.1 on 2023-05-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Франшиза"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="shop",
            name="product",
        ),
        migrations.AddField(
            model_name="shop",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.brand",
                verbose_name="Франшиза",
            ),
        ),
    ]
