# Generated by Django 4.2.1 on 2023-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_brand_remove_shop_product_shop_brand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Франшиза", "verbose_name_plural": "Франшизы"},
        ),
        migrations.AlterModelTable(
            name="brand",
            table="Brand",
        ),
    ]
