# Generated by Django 4.2.1 on 2023-07-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_shop_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="typeshop",
        ),
        migrations.AddField(
            model_name="brand",
            name="type_shop",
            field=models.CharField(
                choices=[
                    ("Зоомагазин", "Зоомагазин"),
                    ("Аптека", "Аптека"),
                    ("Магазин одежды", "Магазин одежды"),
                    ("Товары для дома", "Товары для дома"),
                    ("Продуктовый", "Продуктовый"),
                ],
                default="Продуктовый",
                max_length=20,
                verbose_name="Тип мигазина",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="multiple",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество товара"
            ),
        ),
    ]
