# Generated by Django 4.2.1 on 2023-07-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_brand_typeshop_brand_type_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="multiple",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Количество товара"
            ),
        ),
    ]
