# Generated by Django 4.2.1 on 2023-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_brand_options_alter_brand_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="products",
            field=models.ManyToManyField(related_name="Products", to="shop.product"),
        ),
    ]
