# Generated by Django 4.2.1 on 2023-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_shop_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="typeshop",
            field=models.CharField(
                choices=[
                    ("Зоомагазин", "Зоомагазин"),
                    ("Аптека", "Аптека"),
                    ("Магазин одежды", "Магазин одежды"),
                    ("Товары для дома", "Товары для дома"),
                    ("Продуктовый", "Продуктовый"),
                ],
                default="Продуктовый",
                max_length=20,
                verbose_name="Тип мигазина",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("крупы", "Крупы"),
                    ("молоко", "Молочная продукция"),
                    ("мясо", "Мясо"),
                    ("рыба", "Рыба"),
                    ("фрукты", "Фрукты"),
                    ("овощи", "Овощи"),
                    ("алкоголь", "Алкоголь"),
                ],
                default="молоко",
                max_length=8,
                verbose_name="Тип продукта:",
            ),
        ),
    ]
